input {
    kb_layout = dk
    kb_variant = nodeadkeys
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.

    accel_profile = linear
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace