local o = vim.opt
o.relativenumber = true
o.number = true 
o.signcolumn = 'yes'
o.scrolloff = 10 
o.expandtab = true
o.tabstop = 4
o.smartindent = true
o.wrap = false
o.swapfile = false
o.backup = false
o.undofile = true
o.hlsearch = false
o.incsearch = true
o.termguicolors = true
o.smartindent = true
o.updatetime = 50